#!/usr/bin/env python3
"""scripts/build_site_metadata.py — Synchronize site metadata from site_config.py.

Usage:
    python scripts/build_site_metadata.py          # update public metadata files
    python scripts/build_site_metadata.py --check  # verify files are in sync
"""
import argparse
import re
import sys
from pathlib import Path

# Add project root to sys.path
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import site_config

PUBLIC_DIR = ROOT / "public"
INDEX_HTML = PUBLIC_DIR / "index.html"
SITEMAP_XML = PUBLIC_DIR / "sitemap.xml"
ROBOTS_TXT = PUBLIC_DIR / "robots.txt"
CONFIG_JS = PUBLIC_DIR / "src" / "config.js"

SNAPSHOT_DATE = "2026-09-30"


def generate_config_js() -> str:
    return (
        "// Generated by scripts/build_site_metadata.py from site_config.py — DO NOT EDIT DIRECTLY\n"
        f"export const SITE_URL = '{site_config.SITE_URL}';\n"
        f"export const COMPANY_URL = '{site_config.COMPANY_URL}';\n"
    )


def generate_sitemap_xml() -> str:
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        "  <url>\n"
        f"    <loc>{site_config.SITE_URL}/</loc>\n"
        f"    <lastmod>{SNAPSHOT_DATE}</lastmod>\n"
        "    <changefreq>monthly</changefreq>\n"
        "    <priority>1.0</priority>\n"
        "  </url>\n"
        "</urlset>\n"
    )


def generate_robots_txt() -> str:
    return (
        "User-agent: *\n"
        "Allow: /\n"
        "Disallow: /api/\n"
        "Disallow: /scripts/\n"
        "\n"
        f"Sitemap: {site_config.SITE_URL}/sitemap.xml\n"
    )


def update_index_html(html: str) -> str:
    # 1. Canonical
    html = re.sub(
        r'<link\s+rel="canonical"\s+href="[^"]*"\s*/?>',
        f'<link rel="canonical" href="{site_config.SITE_URL}/">',
        html,
    )

    # 2. Favicons and apple-touch-icon
    fav_block = (
        '  <link rel="icon" href="/favicon.svg" type="image/svg+xml">\n'
        '  <link rel="icon" href="/favicon-32.png" sizes="32x32" type="image/png">\n'
        '  <link rel="alternate icon" href="/favicon.ico" type="image/x-icon">\n'
        '  <link rel="apple-touch-icon" href="/apple-touch-icon.png" sizes="180x180">'
    )
    # Replace existing favicon links
    html = re.sub(
        r'(?:  <link\s+rel="(?:icon|alternate icon|apple-touch-icon)"[^>]*>\n?)+',
        fav_block + "\n",
        html,
    )

    # 3. Open Graph
    html = re.sub(
        r'<meta\s+property="og:url"\s+content="[^"]*"\s*/?>',
        f'<meta property="og:url" content="{site_config.SITE_URL}/">',
        html,
    )

    og_img_block = (
        f'  <meta property="og:image" content="{site_config.SITE_URL}/og-image.png">\n'
        '  <meta property="og:image:width" content="1200">\n'
        '  <meta property="og:image:height" content="630">\n'
        '  <meta property="og:image:alt" content="IHSG Storm \u2014 Pantau kepemilikan saham dan pergerakan investor kakap">'
    )

    # Check if og:image already present
    if '<meta property="og:image"' in html:
        html = re.sub(
            r'^[ \t]*<meta\s+property="og:image"\s+content="[^"]*"\s*/?>\n?'
            r'(?:^[ \t]*<meta\s+property="og:image:width"\s+content="[^"]*"\s*/?>\n?)?'
            r'(?:^[ \t]*<meta\s+property="og:image:height"\s+content="[^"]*"\s*/?>\n?)?'
            r'(?:^[ \t]*<meta\s+property="og:image:alt"\s+content="[^"]*"\s*/?>\n?)?',
            og_img_block + "\n",
            html,
            flags=re.MULTILINE,
        )
    else:
        # Insert after og:locale
        html = re.sub(
            r'(^[ \t]*<meta\s+property="og:locale"\s+content="[^"]*"\s*/?>)',
            r'\1\n' + og_img_block,
            html,
            flags=re.MULTILINE,
        )

    # 4. Twitter Card image
    tw_img_line = f'  <meta name="twitter:image" content="{site_config.SITE_URL}/og-image.png">'
    if '<meta name="twitter:image"' in html:
        html = re.sub(
            r'^[ \t]*<meta\s+name="twitter:image"\s+content="[^"]*"\s*/?>',
            tw_img_line,
            html,
            flags=re.MULTILINE,
        )
    else:
        # Insert after twitter:description
        html = re.sub(
            r'(^[ \t]*<meta\s+name="twitter:description"\s+content="[^"]*"\s*/?>)',
            r'\1\n' + tw_img_line,
            html,
            flags=re.MULTILINE,
        )

    # 5. JSON-LD url
    html = re.sub(
        r'("url":\s*)"https?://[^"]*"',
        f'\\1"{site_config.SITE_URL}/"',
        html,
        count=1,
    )
    # Creator url
    html = re.sub(
        r'("name":\s*"BAD AI",\s*"url":\s*)"https?://[^"]*"',
        f'\\1"{site_config.COMPANY_URL}"',
        html,
    )

    return html


def build(check: bool = False) -> bool:
    all_ok = True

    # 1. public/src/config.js
    expected_config_js = generate_config_js()
    CONFIG_JS.parent.mkdir(parents=True, exist_ok=True)
    if CONFIG_JS.exists():
        current_config_js = CONFIG_JS.read_text(encoding="utf-8")
    else:
        current_config_js = ""

    if current_config_js != expected_config_js:
        if check:
            print(f"[CHECK FAILED] {CONFIG_JS.relative_to(ROOT)} is out of sync")
            all_ok = False
        else:
            CONFIG_JS.write_text(expected_config_js, encoding="utf-8")
            print(f"[UPDATED] {CONFIG_JS.relative_to(ROOT)}")
    else:
        print(f"[IN SYNC] {CONFIG_JS.relative_to(ROOT)}")

    # 2. public/sitemap.xml
    expected_sitemap = generate_sitemap_xml()
    current_sitemap = SITEMAP_XML.read_text(encoding="utf-8") if SITEMAP_XML.exists() else ""
    if current_sitemap != expected_sitemap:
        if check:
            print(f"[CHECK FAILED] {SITEMAP_XML.relative_to(ROOT)} is out of sync")
            all_ok = False
        else:
            SITEMAP_XML.write_text(expected_sitemap, encoding="utf-8")
            print(f"[UPDATED] {SITEMAP_XML.relative_to(ROOT)}")
    else:
        print(f"[IN SYNC] {SITEMAP_XML.relative_to(ROOT)}")

    # 3. public/robots.txt
    expected_robots = generate_robots_txt()
    current_robots = ROBOTS_TXT.read_text(encoding="utf-8") if ROBOTS_TXT.exists() else ""
    if current_robots != expected_robots:
        if check:
            print(f"[CHECK FAILED] {ROBOTS_TXT.relative_to(ROOT)} is out of sync")
            all_ok = False
        else:
            ROBOTS_TXT.write_text(expected_robots, encoding="utf-8")
            print(f"[UPDATED] {ROBOTS_TXT.relative_to(ROOT)}")
    else:
        print(f"[IN SYNC] {ROBOTS_TXT.relative_to(ROOT)}")

    # 4. public/index.html
    if INDEX_HTML.exists():
        current_html = INDEX_HTML.read_text(encoding="utf-8")
        expected_html = update_index_html(current_html)
        if current_html != expected_html:
            if check:
                print(f"[CHECK FAILED] {INDEX_HTML.relative_to(ROOT)} is out of sync")
                all_ok = False
            else:
                INDEX_HTML.write_text(expected_html, encoding="utf-8")
                print(f"[UPDATED] {INDEX_HTML.relative_to(ROOT)}")
        else:
            print(f"[IN SYNC] {INDEX_HTML.relative_to(ROOT)}")

    return all_ok


def main():
    parser = argparse.ArgumentParser(description="Synchronize site metadata from site_config.py")
    parser.add_argument("--check", action="store_true", help="Check if files are up to date without modifying")
    args = parser.parse_args()

    ok = build(check=args.check)
    if not ok:
        sys.exit(1)
    print("Site metadata synchronization complete.")


if __name__ == "__main__":
    main()
